"""Second Migration

Revision ID: 4eebb947691a
Revises: e421aea74d76
Create Date: 2022-04-02 23:19:41.984296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eebb947691a'
down_revision = 'e421aea74d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'nickname')
    # ### end Alembic commands ###
